Apply a fix suggested by Andy
JAVA_HOME should be taken into account now.

diff --git a/jena-fuseki2/apache-jena-fuseki/fuseki-server b/jena-fuseki2/apache-jena-fuseki/fuseki-server
--- a/jena-fuseki2/apache-jena-fuseki/fuseki-server
+++ b/jena-fuseki2/apache-jena-fuseki/fuseki-server
@@ -61,7 +61,29 @@ export FUSEKI_BASE="${FUSEKI_BASE:-$PWD/run}"
 
 JVM_ARGS=${JVM_ARGS:--Xmx1200M}
 
-exec java  $JVM_ARGS -jar "$JAR" "$@"
+#
+# Is JDK available? 
+#
+if [ -z "$JAVA" ]
+then
+    if [ -z "$JAVA_HOME" ]
+    then
+       JAVA=$(which java)
+    else
+       JAVA=$JAVA_HOME/bin/java
+    fi
+fi
+
+if [ -z "$JAVA" ]
+then
+  echo "Cannot find a Java JDK. Please set either set JAVA or put java (>=1.8) in your PATH." 2>&2
+  exit 1
+fi
+
+#
+# Start the server ...
+#
+exec $JAVA $JVM_ARGS -jar "$JAR" "$@"
 
 ## Adding custom code to the Fuseki server:
 ##
